---
- include: setup.yml

- name: disable firewalld
  service: name=firewalld enabled=no state=stopped

# follow instruction from offical docker website https://docs.docker.com/engine/installation/linux/centos/
- name: remove unofficial Docker packages
  yum: name={{item}} state=absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine
  tags:
  - setup
  - dockerrun

# install required packages
- name: remove unofficial Docker packages
  yum: name={{item}} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  tags:
  - setup
  - dockerrun

# add docker.repo
- name: add docker.repo
  template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
  tags:
  - setup
  - dockerrun

- name: install docker
  yum: name=docker-ce state=present
  tags:
  - setup
  - dockerrun

- name: install python-pip to install docker-py
  yum: name=python-pip state=latest
  tags:
  - setup
  - dockerrun

- name: install docker-py
  pip:
    name: docker-py
    state: present
  tags:
  - setup
  - docker-py